import{a as h,S as E,i as d}from"./assets/vendor-6e0bf343.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const y of n.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&a(y)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const w="43225123-d236907a3b16930b7c1176894",L=15;async function m(r,t=1,o=L){const a=`https://pixabay.com/api/?key=${w}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${o}`;try{return(await h.get(a)).data.hits}catch(e){return console.error("Error fetching images:",e),[]}}function p(r){const t=document.getElementById("gallery");t.innerHTML="",r.forEach(o=>{const a=`
        <div class="card">
          <a href="${o.largeImageURL}" data-lightbox="gallery-item">
            <img src="${o.webformatURL}" alt="${o.tags}" data-src="${o.largeImageURL}">
          </a>
          <div class="card-info">
            <span>Likes: ${o.likes}</span>
            <span>Views: ${o.views}</span>
            <span>Comments: ${o.comments}</span>
            <span>Downloads: ${o.downloads}</span>
          </div>
        </div>
      `;t.innerHTML+=a})}const f=document.getElementById("search-form"),u=new E(".gallery a",{captionsData:"alt",captionDelay:250}),b=document.getElementById("gallery"),l=document.getElementById("load-more"),i=document.getElementById("loader");let g="",c=1,s=[];f.addEventListener("submit",async function(r){if(r.preventDefault(),g=f.querySelector('input[name="search"]').value.trim(),!g){d.error({title:"Error",message:"Please enter a search query.",position:"topCenter"});return}try{c=1;const t=await m(g,c);if(t.length===0){d.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again.",position:"topCenter"});return}s=t,p(s),u.refresh(),t.length>=15?l.style.display="block":l.style.display="none"}catch(t){console.error("Error searching images:",t),d.error({title:"Error",message:"An error occurred while searching for images. Please try again later.",position:"topCenter"})}});l.addEventListener("click",async function(){i.style.display="block";try{c++;const r=await m(g,c);s=s.concat(r),p(s),u.refresh(),i.style.display="none",r.length<15&&(l.style.display="none")}catch(r){console.error("Error loading more images:",r),d.error({title:"Error",message:"An error occurred while loading more images. Please try again later.",position:"topCenter"}),i.style.display="none"}});l.addEventListener("click",async function(){i.style.display="block";try{c++;const r=await m(g,c);s=s.concat(r),p(s),u.refresh(),i.style.display="none",r.length<15&&(l.style.display="none");const t=b.querySelector(".card").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}catch(r){console.error("Error loading more images:",r),d.error({title:"Error",message:"An error occurred while loading more images. Please try again later.",position:"topCenter"}),i.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
