import{a as E,S as w,i}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const g of n.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&s(g)}).observe(document,{childList:!0,subtree:!0});function t(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=t(e);fetch(e.href,n)}})();const L="43225123-d236907a3b16930b7c1176894",b=15;async function y(o,r=1,t=b){const s=`https://pixabay.com/api/?key=${L}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${t}`;try{return(await E.get(s)).data.hits}catch(e){return console.error("Error fetching images:",e),[]}}function h(o){const r=document.getElementById("gallery");r.innerHTML="",o.forEach(t=>{const s=`
        <div class="card">
          <a href="${t.largeImageURL}" data-lightbox="gallery-item">
            <img src="${t.webformatURL}" alt="${t.tags}" data-src="${t.largeImageURL}">
          </a>
          <div class="card-info">
            <span>Likes: ${t.likes}</span>
            <span>Views: ${t.views}</span>
            <span>Comments: ${t.comments}</span>
            <span>Downloads: ${t.downloads}</span>
          </div>
        </div>
      `;r.innerHTML+=s})}const u=document.getElementById("search-form"),f=new w(".gallery a",{captionsData:"alt",captionDelay:250}),p=document.getElementById("gallery"),c=document.getElementById("load-more"),m=document.getElementById("loader");let l="",d=1,a=[];u.addEventListener("submit",async function(o){if(o.preventDefault(),p.innerHTML="",a=[],d=1,l=u.querySelector('input[name="search"]').value.trim(),!l){i.error({title:"Error",message:"Please enter a search query.",position:"topCenter"});return}try{const r=await y(l,d);if(r.length===0){i.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again.",position:"topCenter"});return}a.push(...r),h(a),f.refresh();const t=p.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),r.length>=15?c.style.display="block":c.style.display="none"}catch(r){console.error("Error searching images:",r),i.error({title:"Error",message:"An error occurred while searching for images. Please try again later.",position:"topCenter"})}});c.addEventListener("click",async function(){m.style.display="block";try{d++;const o=await y(l,d);a.push(...o),h(a),f.refresh(),m.style.display="none",o.length<15&&(c.style.display="none");const r=p.lastElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch(o){console.error("Error loading more images:",o),i.error({title:"Error",message:"An error occurred while loading more images. Please try again later.",position:"topCenter"}),m.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
